# Generated by Django 6.0.2 on 2026-02-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Title', models.CharField()),
                ('Quantity', models.IntegerField()),
                ('Author', models.CharField(max_length=100)),
                ('ISBN', models.IntegerField()),
                ('Published_Date', models.DateField()),
            ],
        ),
    ]
